#!/bin/zsh

# 我自己用的打包脚本，放在这里方便维护

set -e

version=$(cat VERSION)

rm -rf VimDesktop
mkdir VimDesktop

cp * VimDesktop -r 2>/dev/null || true
cp /mnt/c/mine/app/AutoHotkey/AutoHotkeyU32.exe VimDesktop/vimd.exe
rm -f VimDesktop/conf/vimd.ini
rm -f VimDesktop/custom.ahk
rm -f VimDesktop/build
rm -rf VimDesktop/VimDesktop
rm -rf VimDesktop/doc/wiki/.git

a VimDesktop-$version.7z VimDesktop
mv VimDesktop-$version.7z ~/tmp

cp /mnt/c/mine/app/AutoHotkey/AutoHotkeyU64.exe VimDesktop/vimd.exe
a VimDesktop-x86_64-$version.7z VimDesktop
mv VimDesktop-x86_64-$version.7z ~/tmp

rm -rf VimDesktop
